defaults:
  - _self_
  - data: skin
  - model: swin
  # - model: regNet / swin
pl_trainer:   
  # max_epochs: 100
  # devices: [0]
  accelerator: 'gpu'

hydra:
  job:
    name: swin_v2_t_100ep_full_augm
    # regnety32gf_ch2_pretrained
    # swinv2t_ch2_pretrained
  run:
    dir: outputs/${hydra.job.name}
checkpoint_path: lightning_logs/version_1/checkpoints/epoch=27-valid_acc=0.9239.ckpt