defaults:
  - _self_
  - data: skin
  - model: regNet
  # - model: regNet / swin
pl_trainer:
  max_epochs: 30
  devices: [0]
  accelerator: 'gpu'

hydra:
  job:
    name: regnet_y_3_2gf_full_augm
  run:
    dir: outputs/${hydra.job.name}