defaults:
  - _self_
  - data: skin
  - model: swin
  # - model: regNet / swin
pl_trainer:
  max_epochs: 100
  devices: [0]
  accelerator: 'gpu'

hydra:
  job:
    name: swin_v2_t_100ep_no_augm
  run:
    dir: outputs/${hydra.job.name}