defaults:
  - _self_
  - data: skin
  - model: swin
  # - model: regNet / swin
pl_trainer:
  max_epochs: 60
  devices: [1]
  accelerator: 'gpu'

hydra:
  job:
    name: swin_small_v2_full_augm
  run:
    dir: outputs/${hydra.job.name}