defaults:
  - _self_
  - data: skin
  - model: regNet
  # - model: regNet / swin
pl_trainer:
  max_epochs: 100
  devices: [0]
  accelerator: 'gpu'

hydra:
  job:
    name: regnety32gf_ch2_pretrained_focal
    # regnety32gf_ch2_pretrained
    # swinv2t_ch2_pretrained
  run:
    dir: outputs/${hydra.job.name}