defaults:
  - _self_
  - data: skin
  - model: swin
  # - model: regNet / swin
pl_trainer:
  max_epochs: 60
  devices: [2]
  accelerator: 'gpu'

hydra:
  job:
    name: swin_small_100ep_fullaug_v2_2
  run:
    dir: outputs/${hydra.job.name}