defaults:
  - _self_
  - data: skin
  - model: regNet
  # - model: regNet / swin / swinregnet
pl_trainer:   
  max_epochs: 100
  devices: [1]
  accelerator: 'gpu'

hydra:
  job:
    name: regnety32gf_pretrain_imagenet
    # regnety32gf_ch2_pretrained
    # swinv2t_ch2_pretrained
    # ens_freeze
  run:
    dir: outputs/${hydra.job.name}