defaults:
  - _self_
  - data: skin
  - model: regNet
  # - model: regNet / swin
pl_trainer:
  max_epochs: 100
  devices: [0]
  accelerator: 'gpu'

hydra:
  job:
    name: regnet_y_3_2gf_100ep_full_augm
  run:
    dir: outputs/${hydra.job.name}