defaults:
  - _self_
  - data: skin
  - model: regNet

pl_trainer:
  max_epochs: 20
  devices: [0]
  accelerator: 'gpu'

hydra:
  job:
    name: regNet800_wAugm #SET THE EXPERIMENT NAME
  run:
    dir: outputs/${hydra.job.name}