defaults:
  - _self_
  - data: skin
  - model: swin
  # - model: regNet / swin / swinregnet
pl_trainer:   
  max_epochs: 100
  devices: [0]
  accelerator: 'gpu'

hydra:
  job:
    name: swinv2t_ch2_pretrained_mwnl_cls
    # regnety32gf_ch2_pretrained
    # swinv2t_ch2_pretrained
    # ens_freeze
  run:
    dir: outputs/${hydra.job.name}