_target_: skin_lesion_cad.training.models.ensemble.ConvTransformerEnsemble
num_classes: 2
regnet_chkp_path : /home/user0/cad_vlanasi/skin-lesion-cad/outputs/regnety32gf_pretrain_imagenet_tune2class/lightning_logs/version_1/checkpoints/epoch=28-valid_acc=0.9136.ckpt
swin_chkp_path : /home/user0/cad_vlanasi/skin-lesion-cad/outputs/swinv2t_pretrain_imagenet_tune2class/lightning_logs/version_1/checkpoints/epoch=23-valid_acc=0.9368.ckpt
loss: cross_entropy # cross_entropy, focal, tversky or mwnl
device: 0
freeze : False # whether to freeze the backbones or not
lr: 0.00005