_target_: skin_lesion_cad.training.models.swin.SwinModel
num_classes: 3 # 8 for pretext task
weights: 'IMAGENET1K_V1'
model_class: 'swin_v2_t'
loss: cross_entropy # cross_entropy, focal, tversky or mwnl
device: 1
# if None, train from scratch, otherwise chkp path
chkp_pretrained: /home/user0/cad_vlanasi/skin-lesion-cad/outputs/swinv2t_pretrain_imagenet_tune2class/lightning_logs/version_1/checkpoints/epoch=23-valid_acc=0.9368.ckpt #'/home/user0/cad_vlanasi/skin-lesion-cad/outputs/swin_v2_t_100ep_full_augm/lightning_logs/version_1/checkpoints/epoch=27-valid_acc=0.9239.ckpt' 