_target_: skin_lesion_cad.training.models.swin.SwinModel
num_classes: 8 # 8 for pretext task
weights: 'IMAGENET1K_V1'
model_class: 'swin_v2_t'
loss: focal # cross_entropy, focal, tversky or mwnl
device: 0
# if None, train from scratch, otherwise chkp path
chkp_pretrained: None #'/home/user0/cad_vlanasi/skin-lesion-cad/outputs/swin_v2_t_100ep_full_augm/lightning_logs/version_1/checkpoints/epoch=27-valid_acc=0.9239.ckpt' 